## Word2Vec

In [2]:
import numpy as np
np.random.seed(42)
v_revenge = np.array([0,0,1,0,0,0]) #"revenge"
print(v_revenge)
#array([0, 0, 1, 0, 0, 0])
weight = np.random.random_sample((6,3))
print(weight)
# array([[ 0.43194502,  0.29122914,  0.61185289],
#        [ 0.13949386,  0.29214465,  0.36636184],
#        [ 0.45606998,  0.78517596,  0.19967378],
#        [ 0.51423444,  0.59241457,  0.04645041],
#        [ 0.60754485,  0.17052412,  0.06505159],
#        [ 0.94888554,  0.96563203,  0.80839735]])

hidden_layer_sg = np.dot(v_revenge,weight)
print(hidden_layer_sg)
#array([ 0.45606998,  0.78517596,  0.19967378])
weight_prime = np.random.random_sample((3,6))
print(weight_prime)
#array([[ 0.30461377, 0.09767211, 0.68423303, 0.44015249, 0.12203823, 0.49517691],
       # [ 0.03438852, 0.9093204, 0.25877998, 0.66252228, 0.31171108,      0.52006802],
       # [ 0.54671028, 0.18485446, 0.96958463, 0.77513282, 0.93949894,    0.89482735]])
o_the = np.dot(hidden_layer_sg, weight_prime)
print(o_the)
#array([ 0.27508995, 0.79543243, 0.7088466, 0.87571061, 0.48799933, 0.8128538 ])

[0 0 1 0 0 0]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[0.05808361 0.86617615 0.60111501]
[[0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]
[0.7853302  0.79952094 0.24759478 1.02390925 1.1105601  0.54745364]


In [3]:
v_the = np.array([1,0,0,0,0,0]) #"the"
print(v_the)
#array([1, 0, 0, 0, 0, 0])
#weight = menggunakan weight yang sama dengan ilustrasi pada Skip-Gram
hidden_layer_cbow = np.dot(v_the,weight)
print(hidden_layer_cbow)
#array([0.43194502, 0.29122914, 0.61185289])
#weight_prime = menggunakan weight_prime yang sama dengan ilustrasi pada Skip-Gram
o_revenge = np.dot(hidden_layer_cbow, weight_prime)
print(o_revenge)
#array([0.47609761, 0.42011332, 0.96415848, 0.85733473, 0.7183283, 0.91285087])

[1 0 0 0 0 0]
[0.37454012 0.95071431 0.73199394]
[1.04009215 0.98037764 0.46661355 1.23571455 1.3794737  0.77312024]


In [4]:
import numpy as np
np.random.seed(42)
v_revenge = np.array([0,0,1,0,0,0]) #"revenge"
print(v_revenge)
#array([0, 0, 1, 0, 0, 0])
weight = np.random.random_sample((6,3))
print(weight)
# array([[ 0.43194502,  0.29122914,  0.61185289],
#        [ 0.13949386,  0.29214465,  0.36636184],
#        [ 0.45606998,  0.78517596,  0.19967378],
#        [ 0.51423444,  0.59241457,  0.04645041],
#        [ 0.60754485,  0.17052412,  0.06505159],
#        [ 0.94888554,  0.96563203,  0.80839735]])

hidden_layer_sg = np.dot(v_revenge,weight)
print(hidden_layer_sg)
#array([ 0.45606998,  0.78517596,  0.19967378])
weight_prime = np.random.random_sample((3,6))
print(weight_prime)
#array([[ 0.30461377, 0.09767211, 0.68423303, 0.44015249, 0.12203823, 0.49517691],
       # [ 0.03438852, 0.9093204, 0.25877998, 0.66252228, 0.31171108,      0.52006802],
       # [ 0.54671028, 0.18485446, 0.96958463, 0.77513282, 0.93949894,    0.89482735]])
o_best = np.dot(hidden_layer_sg, weight_prime)
print(o_best)
#array([ 0.27508995, 0.79543243, 0.7088466, 0.87571061, 0.48799933, 0.8128538 ])

[0 0 1 0 0 0]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[0.05808361 0.86617615 0.60111501]
[[0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]
[0.7853302  0.79952094 0.24759478 1.02390925 1.1105601  0.54745364]


In [5]:
v_best = np.array([0,1,0,0,0,0]) #"best"
print(v_best)
#array([1, 0, 0, 0, 0, 0])
#weight = menggunakan weight yang sama dengan ilustrasi pada Skip-Gram
hidden_layer_cbow = np.dot(v_best,weight)
print(hidden_layer_cbow)
#array([0.43194502, 0.29122914, 0.61185289])
#weight_prime = menggunakan weight_prime yang sama dengan ilustrasi pada Skip-Gram
o_revenge = np.dot(hidden_layer_cbow, weight_prime)
print(o_revenge)
#array([0.47609761, 0.42011332, 0.96415848, 0.85733473, 0.7183283, 0.91285087])

[0 1 0 0 0 0]
[0.59865848 0.15601864 0.15599452]
[0.42451664 0.32344971 0.40759145 0.31176029 0.41795589 0.35267831]
